
version: '3.8'

services:
  mariadb1:
    image: mariadb:latest
    container_name: mariadb1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ranem
      MYSQL_DATABASE: restaurantdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Ranem
    volumes:
      - mariadb1-data:/var/lib/mysql
    networks:
      - my-network1

  qksa-api1:
    build: .
    container_name: qksa-api1
    environment:
      DB_HOST: mariadb1
      DB_USER: root
      DB_PASSWORD: Ranem
      DB_NAME: restaurantdb
      DB_PORT: 3306
      PORT: 9999
    ports:
      - "9999:9999"
    depends_on:
      - mariadb
    networks:
      - my-network1

volumes:
  mariadb-data:

networks:
  my-network1:
    driver: bridge 